### ISSUE TITLE
Incorrect country code of London region

### ISSUE THREAD

**Issue by nguyentoanit** [ScaleLeap/amazon-marketplaces#122]
`AmazonMarketplaceAdvertisingCountryCode` enum contains GB country code. But i think it's incorrect. It should be UK.

Ref: [Regional profile time zone codes](https://advertising.amazon.com/API/docs/en-us/reference/2/profiles)

**Comment by moltar** [comment]
Hm, that is an interesting observation!

In [MWS docs](https://docs.developer.amazonservices.com/en_US/dev_guide/DG_Endpoints.html), they use `GB`.

That is the official [ISO country code](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes).

I'm going to open an issue with Amazon Advertising team in Jira.

Is this `UK` value used anywhere as input or output from the API? Or is it just part of the docs?

Thanks

**Comment by moltar** [comment]
Opened a Jira issue `ADAPI-4698`

**Comment by nguyentoanit** [comment]
It is output from Amazon Advertising API when i get Profile list.
`currencyCode`, `timezone`, `marketplaceStringId` are still fine. But `countryCode` is `UK` not `GB`

```
{
  "profileId": 123456789,
  "countryCode": "UK",
  "currencyCode": "GBP",
  "dailyBudget": 0.0,
  "timezone": "Europe/London",
  "accountInfo": {
    "marketplaceStringId": "A1F83G8C2ARO7P",
    "id": "XXXXXX",
    "type": "seller"
  }
}
```
