### ISSUE TITLE
How to add custom time zones to AmazonMarketplaceAdvertisingTimeZone

### ISSUE THREAD

**Issue by sravyadalavai-vl** [ScaleLeap/amazon-marketplaces#365]
I am connecting to amazon api through ScaleLeap/amazon-advertising-api-sdk. While using the profile api i am getting error :
Invalid value "Europe/Amsterdam" supplied to Array. Later I debugged the code, then i found that the particular time zone is not available in time zone list. Could please add it by your self or give the sample code for how to add extra time zones to that list.
If i added these lines  
 EUROPE_AMSTERDAM = "Europe/Amsterdam"
AmazonMarketplaceAdvertisingTimeZone["EUROPE_AMSTERDAM"] = "Europe/Amsterdam";
 in amazon-marketplace.d.ts, amazon-marketplace.js then profile api returning the profiles list.

**Comment by moltar** [comment]
Is this for `NL` marketplace?

[The docs](https://advertising.amazon.com/API/docs/en-us/reference/2/profiles#/Profiles/listProfiles) do say it is supposed to be `Europe/Paris`, so there seems to be a mismatch.

![image](https://user-images.githubusercontent.com/491247/116185371-a9e9f500-a74b-11eb-88a6-12186a4d7ef3.png)

**Comment by sravyadalavai-vl** [comment]
Yes for country Code NL. I am getting this response from api
{"countryCode":"NL","currencyCode":"EUR","dailyBudget":999999999,"timezone":"Europe/Amsterdam","accountInfo":{"marketplaceStringId":".....","id":".....","type":"......","name":"....."}}

**Comment by moltar** [comment]
Ok, thanks. Opened a ticket `ADAPI-8644` with AA Jira to confirm this change. I will fix once they confirm that implementation is in fact the source truth and not the docs.

Thanks for reporting.
