### ISSUE TITLE
Marketplace A21TJRUUN4KGV does not have advertising

### ISSUE THREAD

**Issue by NishealJ** [ScaleLeap/amazon-marketplaces#421]
India has advertising, maintained from EU region.

I tried amazonMarketplaces.AE (which is from EU region) I was able to create and refresh the token but while using the operations of https://github.com/ScaleLeap/amazon-advertising-api-sdk it throws an error  `DecodeError: Invalid value "IN" supplied :` probably because `IN` is not in AmazonMarketplaceCountryCode, currency, etc.

**Comment by NishealJ** [comment]
@moltar can you please take alook? I added it here https://github.com/NishealJ/amazon-marketplaces/commit/5e7a05d3060cf22701b91cf348476d8cceec5e8f

**Comment by moltar** [comment]
@NishealJ it appears that India was not yet officially added to the [documentation](https://advertising.amazon.com/API/docs/en-us/get-started/overview).

Sometimes Amazon releases the advertising feature privately and does not yet want the public to use it. This has happened with other marketplaces as well.

Your PR looks good. But how do you know this information is valid? Why is it in EU? Where did you get the bid info?

If you believe this is accurate, and you have sources to confirm this, then please create a PR.

Cheers!

**Comment by moltar** [comment]
I have asked in Jira to clarify this.

Ticket `ADAPI-11024`.

**Comment by NishealJ** [comment]
@moltar I really appreciate the quick response.

I was using https://github.com/amzn/amazon-advertising-api-php-sdk before with IN marketplace and that worked fine.
I have also used ads api operations with postman using an Indian seller account.

Raise a PR #422 

Thanks!
