### ISSUE TITLE
Can you add new marketplace country codes PL and SE.

### ISSUE THREAD

**Issue by sravyadalavai-vl** [ScaleLeap/amazon-marketplaces#469]
I am trying to get the list of profiles from my amazon account. the list of profiles contains country codes PL and SE and timezones for that countries. but those are not available in the API.  can you please update those lists. i need 
country code: SE,PL.
timezone: "Europe/Stockholm", "Europe/Warsaw".
currency code: SEK,PLN.
API having the below details in static list.
export declare enum AmazonMarketplaceAdvertisingCountryCode {
    AE = "AE",
    AU = "AU",
    BR = "BR",
    CA = "CA",
    DE = "DE",
    ES = "ES",
    FR = "FR",
    IN = "IN",
    IT = "IT",
    JP = "JP",
    MX = "MX",
    NL = "NL",
    SG = "SG",
    UK = "UK",
    US = "US"
}
export declare enum AmazonMarketplaceAdvertisingTimeZone {
    AMERICA_LOS_ANGELES = "America/Los_Angeles",
    AMERICA_SAO_PAULO = "America/Sao_Paulo",
    ASIA_DUBAI = "Asia/Dubai",
    ASIA_INDIA = "Asia/Kolkata",
    ASIA_SINGAPORE = "Asia/Singapore",
    ASIA_TOKYO = "Asia/Tokyo",
    AUSTRALIA_SYDNEY = "Australia/Sydney",
    EUROPE_AMSTERDAM = "Europe/Amsterdam",
    EUROPE_LONDON = "Europe/London",
    EUROPE_PARIS = "Europe/Paris"
}.
Please add it as soon as possible. my application was dependent on it.

**Comment by sravyadalavai-vl** [comment]
after this update can you please update amazon-marketplaces package version in amazon-advertising-api-sdk module

**Comment by sravyadalavai-vl** [comment]
@scaleleap/amazon-advertising-api-sdk still having "@scaleleap/amazon-marketplaces": "12.0.1" version. please update it to latest release version.
![image](https://user-images.githubusercontent.com/69245200/149779718-0be7687e-0d6a-4989-b8e2-af48599a5776.png)

**Comment by moltar** [comment]
This package already has both countries.

If you need to update the dependency in advertising, please open a PR or issue in that repo.
