### ISSUE TITLE
Add marketplace launch date

### ISSUE THREAD

**Issue by moltar** [ScaleLeap/amazon-marketplaces#556]
Would be good to know when the marketplace had launched (announced).

I've asked ChatGPT for this, and here's the result. But need to validate it. 

---

| Amazon Marketplace Country Name | Amazon Marketplace ID | Date when the marketplace launched |
|---------------------------------|-----------------------|-------------------------------------|
| United States                   | US                    | July 1995                           |
| United Kingdom                  | UK                    | October 1998                        |
| Germany                         | DE                    | October 1998                        |
| France                          | FR                    | August 2000                         |
| Japan                           | JP                    | November 2000                       |
| Canada                          | CA                    | June 2002                           |
| China                           | CN                    | September 2004                      |
| Italy                           | IT                    | November 2010                       |
| Spain                           | ES                    | September 2011                      |
| India                           | IN                    | June 2013                           |
| Mexico                          | MX                    | June 2013                           |
| Australia                       | AU                    | April 2018                          |
| Brazil                          | BR                    | January 2019                        |
| United Arab Emirates            | AE                    | May 2019                            |
| Singapore                       | SG                    | October 2019                        |
| Saudi Arabia                    | SA                    | June 2020                           |
| Netherlands                     | NL                    | March 2020                          |
| Sweden                          | SE                    | October 2020                        |
| Poland                          | PL                    |                                     |

**Comment by nguyentoanit** [comment]
@moltar : I couldn't find out an official documentations about this one.
From my point of view, We can consider Wikipedia as a good quarter? 

Here are the differences between [Wikipedia](https://en.wikipedia.org/wiki/Amazon_(company)#Amazon.com) and ChatGPT result:

| Amazon Marketplace Country Name | Date when the marketplace launched |
|---------------------------------|------------------------------------|
| Mexico                          | August 2013                        |
| Australia                       | November 2017                      |
| Brazil                          | December 2012                      |
| Singapore                       | July 2017                          |
| Netherlands                     | November 2014                      |
| Poland                          | March 2021                         |

**Comment by nguyentoanit** [comment]
I'm thinking of adding a new field in [marketplace object](https://github.com/ScaleLeap/amazon-marketplaces/blob/master/src/amazon-marketplace.ts) as well.
Perhaps, A new field in string type is enough?

**Comment by nguyentoanit** [comment]
What is use case of this field?

**Comment by moltar** [comment]
ChatGPT definitely lies. This was just a draft and a quick example. We certainly should use more official sources like Wikipedia for this.
