### ISSUE TITLE
SA is EU region for amazon ads.

### ISSUE THREAD

**Issue by NishealJ** [ScaleLeap/amazon-marketplaces#592]
Hi,

Saudi Arabia is EU region for amazon ads, hence the endpoint should be `marketplaceAdvertisingRegions.EU,`

**Comment by moltar** [comment]
@nguyentoanit Please confirm this to be true and apply the fix from the PR.

**Comment by nguyentoanit** [comment]
It's true! See this doc: https://advertising.amazon.com/API/docs/en-us/guides/amazon-marketing-cloud/get-started/make-your-first-call#tag/Profiles/operation/getProfileById

<img width="539" alt="image" src="https://github.com/ScaleLeap/amazon-marketplaces/assets/19872073/4121c113-5ba4-43d6-a185-e107de3f8dde">
