### ISSUE TITLE
Migration from 17.3.0 to 18.0.0 - Cannot find module '@scaleleap/amazon-marketplaces' or its corresponding type declarations

### ISSUE THREAD

**Issue by xhuberdeau** [ScaleLeap/amazon-marketplaces#634]
Hello,

Thanks for this repository!

I'm trying to migrate this dependency from 17.3.0 to 18.0.0 but typescript shows me an error:
![image](https://github.com/ScaleLeap/amazon-marketplaces/assets/7859143/97874711-6ad1-4587-a05b-d8abc7685bda).

I digged a bit hoping this might help: the difference I see in the node_modules between 17.3.0 and 18.0.0 is that now, the lib files are not directly in the lib folder but in a src subfolder. So the `types` property in the package.json seems wrong as it's pointing to a non-existing file (it should be `lib/src/index.d.ts` instead of `lib/index.d.ts`)

### Version 17.3.0
![image](https://github.com/ScaleLeap/amazon-marketplaces/assets/7859143/cd70b0e1-2ef5-4563-9a49-4c88b0583785)

### Version 18.0.0
![image](https://github.com/ScaleLeap/amazon-marketplaces/assets/7859143/83972b5a-a2fd-4bb3-924d-c94695bb61b7)

Tell me if you need more information :slightly_smiling_face:

**Comment by nguyentoanit** [comment]
@xhuberdeau: This issue should be addressed in `v18.0.1`. 🚀

**Comment by xhuberdeau** [comment]
> @xhuberdeau: This issue should be addressed in `v18.0.1`. 🚀

Wow, thanks for the quick fix :tada:
